In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("p2p-Gnutella06.txt", sep = '	', header = None)
data

0     1
0         0     1
1         0     2
2         0     3
3         0     4
4         0     5
...     ...   ...
31520  8716  4258
31521  8716  4776
31522  8716  5114
31523  8716  8188
31524  8716  8603

[31525 rows x 2 columns]

In [3]:
if data[0].max() >= data[1].max():
    nodes = data[0].max()
else:
    nodes = data[1].max()
nodes += 1
edges = data.shape[0]
print("Number of nodes: ", nodes)
print("Number of edges: ", edges)

Number of nodes:  8717
Number of edges:  31525


In [5]:
#Adjacency list for outgoing edges
adj_out = []
for i in range(nodes):
    adj_out.append(list(data[data[0] == i][1]))
adj_out

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [],
 [],
 [],
 [],
 [],
 [21, 327, 619, 1828, 2173, 2201, 2743, 2744, 2745, 2746],
 [],
 [372, 437, 816, 1826, 1913, 2303, 2734, 2735, 2736, 2737],
 [35, 321, 446, 1184, 1542, 2738, 2739, 2740, 2741, 2742],
 [170, 556, 558, 882, 1059, 2752, 2753, 2754, 2755, 2756],
 [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
 [521, 1274, 1318, 1453, 2348, 2747, 2748, 2749, 2750, 2751],
 [],
 [252, 314, 1725, 2112, 2684, 2757, 2758, 2759, 2760, 2761],
 [],
 [],
 [938, 1608, 2786, 3597, 4038],
 [],
 [],
 [499, 645, 733, 934, 1051, 2806, 2807, 2808, 2809, 2810],
 [],
 [23, 24, 25, 26, 27, 28, 29, 30, 31],
 [35, 463, 1008, 1142, 1225, 1577, 1874, 2769, 2770, 2771],
 [],
 [637, 1695, 1775, 2032, 2986, 3261, 7208, 7255, 7256, 7257],
 [31, 169, 170, 173, 175, 176, 556, 558, 1059, 2762],
 [485, 885, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419],
 [173, 279, 1536, 1538, 2763, 2764, 2765, 2766, 2767, 2768],
 [],
 [],
 [170, 173, 175, 176, 556, 558, 565, 1059, 2762, 2779],
 [33

In [6]:
#Adjacency list for incoming edges
adj_in = []
for i in range(nodes):
    adj_in.append(list(data[data[1] == i][0]))
adj_in

[[260, 1639],
 [0, 977, 3692, 5858],
 [0, 54, 2193, 4846, 7049],
 [0, 568, 1716, 1829, 2079, 2562, 3126, 3987, 4627, 5771, 6749, 7978],
 [0, 2143, 3195, 4897, 6494, 8246],
 [0, 851, 1729, 2189, 2457, 5606, 5839, 5985, 6032, 6838],
 [0, 37, 1011, 1206, 1428, 1604, 1753, 3077, 5759, 7795, 8460],
 [0, 154, 462, 816, 1163, 1322, 1379, 1802, 1813, 2672, 2839, 5191, 7500],
 [0, 907, 1339, 2608, 3551, 3760, 7378],
 [0, 899],
 [0, 1814, 2921, 3692, 4504, 4677, 7210],
 [2202, 3288, 4512, 7406],
 [11, 549, 1517, 4399, 5717],
 [11,
  87,
  461,
  735,
  834,
  857,
  943,
  1242,
  1908,
  2101,
  2259,
  2343,
  3442,
  3495,
  3532,
  3613,
  3758,
  3838,
  4154,
  4351,
  4352,
  5302,
  5371,
  5872,
  6159,
  6716,
  6802,
  6846,
  7212,
  7327,
  7330,
  7354,
  7669,
  7673,
  7943,
  8003],
 [11],
 [11, 636, 1532],
 [11, 411],
 [11, 352, 483, 1713, 2610, 3387, 3391, 7825],
 [11, 916, 1851, 2662, 2895],
 [11, 39, 1937, 2522, 3889, 4994, 5870, 7102, 7818, 8113],
 [11,
  1266,
  1613,
  19

## PageRank

In [11]:
prscores = np.ones(nodes)
prscores = prscores/nodes
prscores

array([0.00011472, 0.00011472, 0.00011472, ..., 0.00011472, 0.00011472,
       0.00011472])

In [12]:
df = 0.85
itr = 100
for i in range(itr):
    for j in range(nodes):
        prscores[j] = 1 - df
        for k in adj_in[j]:
            prscores[j] += ( df * (prscores[k]/len(adj_out[k])))

In [14]:
prscores

array([0.20502458, 0.22492722, 0.36538346, ..., 0.16403571, 0.1732268 ,
       0.16394304])

## Authority and Hub

In [16]:
hub = np.ones(nodes)
auth = np.ones(nodes)
hub, auth

(array([1., 1., 1., ..., 1., 1., 1.]), array([1., 1., 1., ..., 1., 1., 1.]))

In [17]:
itr = 100
for i in range(itr):
    hub_sum = 0
    auth_sum = 0
    for j in range(nodes):
        temp = 0 
        for k in adj_in[j]:
            temp += hub[k]
        auth[j] = temp
        auth_sum += temp
        temp = 0
        for k in adj_out[j]:
            temp += auth[k]
        hub[j] = temp
        hub_sum += temp
    for j in range(nodes):
        hub[j] /= hub_sum
        auth[j] /= auth_sum

In [18]:
hub

array([2.16935250e-13, 0.00000000e+00, 0.00000000e+00, ...,
       9.49573389e-04, 0.00000000e+00, 8.65557026e-04])

In [20]:
auth

array([1.11143957e-10, 1.23428559e-10, 4.37718962e-10, ...,
       6.35960471e-03, 5.73685136e-03, 4.94630151e-04])

## Results

In [40]:
#Node having max prscore
best_prs = np.argmax(prscores)
print("Node having max prscore: ", best_prs, "({})".format(prscores[best_prs]))

Node having max prscore:  556 (1.950733422083331)


In [42]:
#Node having max hub score
best_hub = np.argmax(hub)
print("Node having max Hub score: ", best_hub, "({})".format(hub[best_hub]))

Node having max Hub score:  8566 (0.015125446751113115)


In [43]:
#Node having max auth score
best_auth = np.argmax(auth)
print("Node having max auth score: ", best_auth, "({})".format(auth[best_auth]))

Node having max auth score:  8626 (0.008312806886373312)


In [28]:
scores = pd.DataFrame({"Node" : range(nodes), "PageRank" : prscores, "Hub": hub, "Authority" : auth})
scores

Node  PageRank           Hub     Authority
0        0  0.205025  2.169352e-13  1.111440e-10
1        1  0.224927  0.000000e+00  1.234286e-10
2        2  0.365383  0.000000e+00  4.377190e-10
3        3  0.393537  0.000000e+00  3.257245e-09
4        4  0.243925  0.000000e+00  2.066350e-08
...    ...       ...           ...           ...
8712  8712  0.164036  0.000000e+00  6.359605e-03
8713  8713  0.164036  0.000000e+00  6.359605e-03
8714  8714  0.164036  9.495734e-04  6.359605e-03
8715  8715  0.173227  0.000000e+00  5.736851e-03
8716  8716  0.163943  8.655570e-04  4.946302e-04

[8717 rows x 4 columns]

In [33]:
pr_df = scores.sort_values('PageRank', ascending = False)
pr_df

Node  PageRank           Hub     Authority
556    556  1.950733  4.434699e-06  4.895225e-05
841    841  1.828730  3.634898e-10  5.970036e-07
300    300  1.828251  8.321878e-13  2.641509e-08
558    558  1.823819  3.001334e-08  4.889689e-05
176    176  1.821487  5.246684e-09  3.677327e-06
...    ...       ...           ...           ...
2510  2510  0.150000  2.979959e-06  0.000000e+00
2502  2502  0.150000  3.224085e-12  0.000000e+00
2487  2487  0.150000  1.606938e-06  0.000000e+00
2468  2468  0.150000  9.672897e-08  0.000000e+00
1947  1947  0.150000  3.804624e-06  0.000000e+00

[8717 rows x 4 columns]

In [34]:
hub_df = scores.sort_values('Hub', ascending = False)
hub_df

Node  PageRank       Hub     Authority
8566  8566  0.164444  0.015125  6.477035e-04
8428  8428  0.163957  0.014093  3.443389e-04
8282  8282  0.163935  0.013998  1.254625e-04
8221  8221  0.188218  0.012724  1.067118e-05
8700  8700  0.165126  0.012209  1.602977e-04
...    ...       ...       ...           ...
5327  5327  0.219180  0.000000  6.687019e-05
2508  2508  0.233758  0.000000  5.475374e-05
5325  5325  0.192859  0.000000  1.188802e-05
2512  2512  0.216353  0.000000  1.582020e-06
4358  4358  0.424285  0.000000  6.829929e-09

[8717 rows x 4 columns]

In [36]:
auth_df = scores.sort_values('Authority', ascending = False)
auth_df

Node  PageRank           Hub  Authority
8626  8626  0.177892  0.000000e+00   0.008313
8420  8420  0.179417  0.000000e+00   0.007996
8369  8369  0.177947  2.741504e-04   0.007323
8419  8419  0.163934  1.067486e-04   0.007291
8381  8381  0.165999  5.715331e-04   0.006628
...    ...       ...           ...        ...
2283  2283  0.310318  1.023237e-05   0.000000
7646  7646  0.293329  3.397194e-06   0.000000
2273  2273  0.170334  4.567434e-07   0.000000
2272  2272  0.150000  2.631765e-08   0.000000
2215  2215  0.150000  4.804219e-06   0.000000

[8717 rows x 4 columns]